services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    depends_on:
      - postgres
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=chat_user password=chat_pass dbname=chat_db sslmode=disable
    volumes:
      - ./migrations:/migrations
    command: ["sh", "-c", "goose -dir=/migrations up"]
    restart: "on-failure"

  api:
    build: .
    depends_on:
      - postgres
      - migrations
    environment:
      - DB_DSN=host=postgres user=chat_user password=chat_pass dbname=chat_db port=5432 sslmode=disable
      - HTTP_ADDR=:8080
    ports:
      - "8080:8080"

volumes:
  pgdata: {}
